### ISSUE TITLE
Snap Package fails to install files

### ISSUE THREAD

**Issue by Legot** [RLado/Oink#1]
Running on a very clean Debian 12 installation, snap appears to install the package and dependencies with no issues
````
root@debianTest:~# snap install --beta oink
2023-12-27T15:23:55-07:00 INFO Waiting for automatic snapd restart...
oink (beta) 1.0.1 from Ricard Lado (rlado) installed
````
````
root@debianTest:~# snap list
Name    Version   Rev    Tracking       Publisher   Notes
core22  20231123  1033   latest/stable  canonical✓  base
oink    1.0.1     14     latest/beta    rlado       -
snapd   2.60.4    20290  latest/stable  canonical✓  snapd
````
However there is no directory or config file created at `/etc/oink_ddns/` and there is no service created for oink_ddns:
````
root@debianTest:~# systemctl status oink_ddns
Unit oink_ddns.service could not be found.
````
Critically, the snap directory for oink doesn't contain anything
````
root@debianTest:~# tree snap
snap
└── oink
    ├── 14
    ├── common
    └── current -> 14

5 directories, 0 files
````

Otherwise this is a very cool tool, I think a snap package for distribution is an excellent way to go!

**Comment by RLado** [comment]
Thank you for raising the issue. I have made some modifications to address the problem.

There were two main problems, first the snap package was not copying the configuration file to the $SNAP_COMMON folder. Also, due to snap strict sandboxing the setup process described in this repository is not correct. I will shortly provide proper instructions in the `README.md` file and Snap Store page, meanwhile this is what you need to do:

1. Reinstall the oink package
2. Modify the configuration file at /var/snap/oink/common/config.json adding the necessary data
3. Start the service by running ` snap start --enable oink` 
4. Check that the service is running and no errors appeared using `snap logs oink`
5. Done. Now Oink! should run as a service in the background.

Please, let me know if that solved your problem

**Comment by Legot** [comment]
It is now working flawlessly with those corrections. Thanks!
