### ISSUE TITLE
Odd API responses

### ISSUE THREAD

**Issue by ghost** [RLado/Oink#12]
I started using Oink yesterday, and while it is a great program, I couldn't help but notice this in the systemd logs. I am not really sure what is going on here, since the client is pretty straightforward and I set up the config file correctly. These messages also appeared yesterday, every 3 hours or so.

![image_2024-10-13_13-13-43](https://github.com/user-attachments/assets/1acb3a36-71f7-4377-92f4-2029b5365b38)

![image_2024-10-13_13-15-47](https://github.com/user-attachments/assets/e4259622-d5bb-4d7d-9f83-9b7d274f18de)

**Comment by RLado** [comment]
That's a good question, I have occasionally seen this error as well but always assumed it was an error on Porkbun's side, since the status code reported by Oink is the http code of the request response *(503 Service Unavailable)*. Oink does not log the full response so I do not have much more information than that. In my experience this is a rather rare occurrence, nevertheless, I'll keep an eye on it. This is that kind of error which is difficult to debug because it is inconsistent.

The other issue to be discussed is how Oink handles the error, generally when the program encounters an error it logs, panics, and then systemd restarts the program on a 60s timer. In this case I am guessing Porkbun sends a response body with an html message that when Oink tries to decode as a json response it fails, logs, and exits the program. I think this is acceptable behaviour, but I am open to hearing a different opinion.

**Comment by ghost** [comment]
Interesting, well at least I am not the only one seeing this. I am going to get in touch with them, out of sheer curiosity. See what can be done about it.

**Comment by ghost** [comment]
Well, this was their response:

"Unfortunately that log entry does not give us much to go on, but I'm guessing there is an API command in the client which is being submitted with the invalid character "<". If the developer of the app can implement verbose logging so that you can log the entire command and response it should be much easier to see what the issue is."

I am not sure what to make of it however.

**Comment by RLado** [comment]
They are right about the fact that having a more verbose logging mode would help diagnose the problem, but I am quite certain that the issue is on the response back from Porkbun's server as it returns a [503 status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503). Not trying to shift blame here but this is a temporary server side error. 

What I could do to fix this is to just retry after an error, instead of reporting it. But I think this is really a non-issue, the error is going to happen anyway, the only difference is that you won't be notified.

**Comment by RLado** [comment]
Hey, have you seen this problem pop up again? Maybe this was related to the hostname change for the API. 

>*Friendly reminder to update to version 1.3.1 before December*

**Comment by ghost** [comment]
Now that you mention it... I haven't! I might have ironically scared them since I stopped seeing this message the day they answered my email. Did you use to see these HTTP codes every day?

**Comment by RLado** [comment]
No, it was a rare occurrence. It happens every so often but it is quite unusual (months apart). I guess it happens when they do some kind of server maintenance.

**Comment by 8bitbuddhist** [comment]
Sorry to reopen this, but I just ran into this issue today.  It happens consistently, and I'm not sure what to do other than try a different client

```sh
Nov 08 00:11:54 myHost systemd[1]: Started Dynamic DNS client for Porkbun.
░░ Subject: A start job for unit oink.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit oink.service has finished successfully.
░░ 
░░ The job identifier is 84131.
Nov 08 00:11:57 myHost oink-start[1685432]: 2024/11/08 00:11:57 error decoding API response: invalid character '<' looking for beginning of value (status: 503)
Nov 08 00:11:57 myHost systemd[1]: oink.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit oink.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Nov 08 00:11:57 myHost systemd[1]: oink.service: Failed with result 'exit-code'.
```

**Comment by RLado** [comment]
This error gets triggered by an unexpected response from the Porkbun's server indicating the API service is unavailable, there is no fix for this issue other than waiting.

**Comment by tocklime** [comment]
Just noticed this while adding a domain to my list of things to update. Looking back over the logs of the last few months, I can't find a single successful run, they're all `error decoding API response: invalid character '<' looking for beginning of value (status: 503)`. I imagine I have mis-configured something, but no there is no way to diagnose.

**Comment by tocklime** [comment]
Added some logging and recovered the full error:
```
2025/01/15 12:28:36 error decoding API response: invalid character '<' looking for beginning of value (status: 503)
body:
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

So it really is porkbun returning errors.

... and it's more reliable on the command line than it appears to be in my logs. I suspect some (successful ones) are being omitted/deleted or something 🤷‍♀️.

Anyway, finally got the error message I needed (`400: Domain is not opted in to API access`) - which did appear in the logs eventually.
