### ISSUE TITLE
A and AAAA records. Only ipv6 is getting updated. - Help please!

### ISSUE THREAD

**Issue by xgpt** [RLado/Oink#3]

**Comment by RLado** [comment]
That is expected behaviour as the Porkbun v3 API's documentation is unclear about the response of their `ping` command (it will either return IPv4 or IPv6). However, there is a dedicated endpoint to request IPv4 specifically. Would you be willing to help me test that? My ISP does not provide IPv6 support and so I need someone to test for me. (It should not take me too long)

**Comment by RLado** [comment]
The fix is ready in the `v1.1rc` branch. If anyone is willing to test it, please report back.

**Comment by xgpt** [comment]
thank you for this :)
