### ISSUE TITLE
Debian <= 11 dkpg cannot handle .zst-compression

### ISSUE THREAD

**Issue by jp-berg** [RLado/Oink#4]
Installing the .deb package with any Debian version before 12 will result in the following error:

`
~$ sudo dpkg -i oink.deb
`
`
dpkg-deb: error: archive 'oink.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive oink.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 oink.deb
`

[The fix is to compress with .xz](https://unix.stackexchange.com/a/745467)

**Comment by RLado** [comment]
Thanks for the heads-up. Until I fix it, you can use my [packaging script](https://github.com/RLado/Oink_deb/tree/master) to get a compatible package.

**Comment by jp-berg** [comment]
After continuing my install I think supporting Debian <= 11 is not worth the hassle. Installing the repacked .deb results in a GLIBC-error and you cannot compile from source since the Go-version needed is not in the repos. But thank you for your swift response.

**Comment by RLado** [comment]
You can probably compile using a much lower version of Go than 1.21, the code is fairly simple and does not use generics. I used 1.21 because it is what I have installed in my system. Nevertheless, you will probably have a better experience using something like [ddclient](https://github.com/ddclient/ddclient), which is far more popular and now supports Porkbun.
Alternatively, I guess the snap package probably works fine but it forces you to install *snap* and I understand that not everyone likes it.
