### ISSUE TITLE
FR: Run on systemd timer rather than as a daemon

### ISSUE THREAD

**Issue by catleeball** [RLado/Oink#5]
It would be nice if there were an option to run Oink on a systemd timer launching only at update intervals rather than running as a daemon that calls sleep() on a loop.

Not running as a daemon would reduce the overall memory footprint on machines where it runs, requiring memory only when an update is being performed.

Thanks for making this handy DDNS tool!

**Comment by RLado** [comment]
Thanks for the suggestion! I have added a flag to run the DNS update once and then exit, instead of sleeping in a loop. This way it can be run from a cron job or systemd timer while keeping prior functionality unchanged.

I suggest creating a timer and service file like the following:

```
/usr/lib/systemd/system/oink.timer

-----

[Unit]
Description=Updates Porkbun DNS records on a timer (every 15 minutes)

[Timer]
OnBootSec=0min
OnCalendar=*:0/15

[Install]
WantedBy=timers.target
```

```
/usr/lib/systemd/system/oink.service

-----

[Unit]
Description=Updates Porkbun DNS records

[Service]
ExecStart=/usr/bin/oink -u
```

Then enable and start the timer:

```bash
sudo systemctl enable oink.timer
sudo systemctl start oink.timer
```

**Comment by catleeball** [comment]
That's wonderful, thank a bunch for adding the flag and for the example timer! :)
